DROP TABLE IF EXISTS answer;

DROP TABLE IF EXISTS pool_user;

DROP TABLE IF EXISTS user_id;

DROP SEQUENCE IF EXISTS user_seq;

DROP TABLE IF EXISTS question;

DROP SEQUENCE IF EXISTS question_seq;

DROP TABLE IF EXISTS pool;

DROP SEQUENCE IF EXISTS pool_seq;